### ISSUE TITLE
Cannot find FANN source libs in mutliarch

### ISSUE THREAD

**Issue by randomstuff** [FutureLinkCorporation/fann2#25]
When trying to install this library I get:

<pre>
$ pip install .
Processing /home/johndoe/src/fann2
    Complete output from command python setup.py egg_info:
    Looking for FANN libs...
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-e23ii2o4-build/setup.py", line 92, in <module>
        build_swig()
      File "/tmp/pip-e23ii2o4-build/setup.py", line 85, in build_swig
        find_fann()
      File "/tmp/pip-e23ii2o4-build/setup.py", line 73, in find_fann
        raise Exception("Couldn't find FANN source libs!")
    Exception: Couldn't find FANN source libs!
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-e23ii2o4-build/
</pre>

The reason is that on multiarch systems (at least Debian-based ones) libdoublefann is located in `/usr/lib/$ARCH/libdoublefann.so` (eg. `/usr/lib/x86_64-linux-gnu/libdoublefann.so`)::

Patching the setup code like this fixes the issue:

<pre>
def find_fann():
    '''Find doublefann library'''
    # FANN possible libs directories (as $LD_LIBRARY_PATH), also includes
    # pkgsrc framework support.
    if sys.platform == "win32":
        dirs = sys.path
        for ver in dirs:
            if os.path.isdir(ver):
                if find_x(ver):
                    return True
        raise Exception("Couldn't find FANN source libs!")
    else:
        # Fixed the path here:
        dirs = ['/lib', '/usr/lib/', '/usr/lib/x86_64-linux-gnu', '/usr/lib64', '/usr/local/lib', '/usr/pkg/lib']
        for path in dirs:
            if os.path.isdir(path):
                if find_x(path):
                    return True
        raise Exception("Couldn't find FANN source libs!")
</pre>

**Comment by randomstuff** [comment]
But this is not a correct solution as the correct ARCH to use depends on the architecture of the python interpreter. I'd tend to remove `find_fann()` altogether and just try to compile the thing.

**Comment by randomstuff** [comment]
Another problem with this is that it wont honor `LD_LIBRARY_PATH`.

**Comment by kirkhansen** [comment]
This took me longer than it should have to debug. I spent quite a bit of time trying to understand how the shared file objects were not on the LD_LIBRARY_PATH; turns out they were, and I noticed that `find_fann` function ignored the multiarch directory. 

My workaround was to symlink the shared file objects to one of the listed directories in `find_fann`

I agree with @randomstuff to remove that function and just attempt to compile.
